# Generated by Django 5.0.14 on 2026-02-09 13:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentPhysicalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название типа"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="equipment_types/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "applicable_category",
                    models.CharField(
                        choices=[
                            ("DGU", "Дизельно-генераторная установка"),
                            ("COMPRESSOR", "Компрессорная установка"),
                            ("UNIVERSAL", "Универсальный"),
                        ],
                        default="UNIVERSAL",
                        max_length=20,
                        verbose_name="Применимость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Физический тип оборудования",
                "verbose_name_plural": "Физические типы оборудования",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название категории"),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("DGU", "Дизельно-генераторная установка"),
                            ("COMPRESSOR", "Компрессорная установка"),
                            ("UNIVERSAL", "Универсальный"),
                        ],
                        default="UNIVERSAL",
                        max_length=20,
                        verbose_name="Тип оборудования",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Например: 1.1.1",
                        max_length=50,
                        verbose_name="Код категории",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.equipmentcategory",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория оборудования",
                "verbose_name_plural": "Категории оборудования",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название модуля"),
                ),
                (
                    "applicable_to",
                    models.CharField(
                        choices=[
                            ("DGU", "Только для ДГУ"),
                            ("COMPRESSOR", "Только для компрессоров"),
                            ("BOTH", "Универсальный (для обоих)"),
                        ],
                        default="BOTH",
                        max_length=20,
                        verbose_name="Применимость к оборудованию",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Фиксированная цена"),
                            ("individual", "Индивидуальный расчёт"),
                            ("request", "По запросу"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="Тип цены",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Заполняется только если price_type='fixed'",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="modules/",
                        verbose_name="Основное изображение",
                    ),
                ),
                (
                    "power_consumption",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Потребляемая мощность, Вт"
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Габариты (ШхВхГ)"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Вес, кг",
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительные характеристики в формате JSON",
                        verbose_name="Технические характеристики",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Выбран по умолчанию"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию из иерархии ТЗ",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules_by_category",
                        to="catalog.equipmentcategory",
                        verbose_name="Категория ТЗ",
                    ),
                ),
                (
                    "physical_type",
                    models.ForeignKey(
                        help_text="Физический тип оборудования",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules_by_type",
                        to="catalog.equipmentphysicaltype",
                        verbose_name="Физический тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модуль оборудования",
                "verbose_name_plural": "Модули оборудования",
                "ordering": ["category__order", "physical_type__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompatibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название правила"),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("exclusion", "Взаимоисключение"),
                            ("requirement", "Требование"),
                            ("group", "Группа"),
                            ("limit", "Ограничение количества"),
                            ("category_exclusion", "Исключение по категории"),
                        ],
                        max_length=20,
                        verbose_name="Тип правила",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание правила"),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Для rule_type='limit'",
                        null=True,
                        verbose_name="Максимальное количество",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Для правил, связанных с категориями",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_rules",
                        to="catalog.equipmentcategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "excluded_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Категории, которые становятся недоступными при выборе указанной категории",
                        related_name="excluded_by_rules",
                        to="catalog.equipmentcategory",
                        verbose_name="Исключаемые категории",
                    ),
                ),
                (
                    "modules",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compatibility_rules",
                        to="catalog.equipmentmodule",
                        verbose_name="Модули",
                    ),
                ),
                (
                    "required_module",
                    models.ForeignKey(
                        blank=True,
                        help_text="Для rule_type='requirement'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_by_rules",
                        to="catalog.equipmentmodule",
                        verbose_name="Требуемый модуль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило совместимости",
                "verbose_name_plural": "Правила совместимости",
            },
        ),
        migrations.AddIndex(
            model_name="equipmentcategory",
            index=models.Index(
                fields=["parent", "is_active"], name="catalog_equ_parent__1e9e7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipmentmodule",
            index=models.Index(
                fields=["is_active", "category", "applicable_to"],
                name="catalog_equ_is_acti_41d8ca_idx",
            ),
        ),
    ]
