# Generated by Django 5.0.14 on 2026-02-07 12:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модуля')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_type', models.CharField(choices=[('fixed', 'Фиксированная цена'), ('individual', 'Индивидуальный расчёт'), ('request', 'По запросу')], default='fixed', max_length=20, verbose_name='Тип цены')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Заполняется только если price_type='fixed'", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='modules/', verbose_name='Основное изображение')),
                ('power_consumption', models.IntegerField(blank=True, null=True, verbose_name='Потребляемая мощность, Вт')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Габариты (ШхВхГ)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес, кг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, verbose_name='Выбран по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Модуль оборудования',
                'verbose_name_plural': 'Модули оборудования',
                'ordering': ['equipment_type__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_types/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('rule_type', models.CharField(choices=[('exclusion', 'Взаимоисключение'), ('requirement', 'Требование'), ('group', 'Группа'), ('limit', 'Ограничение количества')], max_length=20, verbose_name='Тип правила')),
                ('description', models.TextField(blank=True, verbose_name='Описание правила')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text="Для rule_type='limit'", null=True, verbose_name='Максимальное количество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('modules', models.ManyToManyField(related_name='compatibility_rules', to='catalog.equipmentmodule', verbose_name='Модули')),
                ('required_module', models.ForeignKey(blank=True, help_text="Для rule_type='requirement'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_by_rules', to='catalog.equipmentmodule', verbose_name='Требуемый модуль')),
            ],
            options={
                'verbose_name': 'Правило совместимости',
                'verbose_name_plural': 'Правила совместимости',
            },
        ),
        migrations.AddField(
            model_name='equipmentmodule',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalog.equipmenttype', verbose_name='Тип оборудования'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodule',
            index=models.Index(fields=['is_active', 'equipment_type'], name='catalog_equ_is_acti_b4027e_idx'),
        ),
    ]
