from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_rename_equipmentmodule_equipment_type_to_category"),
    ]

    operations = [
        migrations.RunSQL(
            sql=r"""
DO $$
BEGIN
    -- 1) Создаём таблицу physical type, если её реально нет в БД
    IF to_regclass('public.catalog_equipmentphysicaltype') IS NULL THEN
        CREATE TABLE public.catalog_equipmentphysicaltype (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name varchar(100) NOT NULL UNIQUE,
            description text NOT NULL DEFAULT '',
            image varchar(100) NULL,
            "order" integer NOT NULL DEFAULT 0,
            applicable_category varchar(20) NOT NULL DEFAULT 'UNIVERSAL'
        );

        -- check как в старых миграциях/моделях
        ALTER TABLE public.catalog_equipmentphysicaltype
            ADD CONSTRAINT catalog_equipmentphysicaltype_order_check CHECK ("order" >= 0);

        CREATE INDEX IF NOT EXISTS catalog_equipmentphysicaltype_applicable_order_idx
            ON public.catalog_equipmentphysicaltype (applicable_category, "order");
    END IF;

    -- 2) Если колонка physical_type_id уже есть в equipmentmodule, то FK добавим позже отдельной миграцией,
    -- потому что сейчас важнее восстановить саму таблицу.
END $$;
""",
            reverse_sql=r"""
-- Откат: таблицу не удаляем (это восстановление схемы, а не “фича”)
""",
        )
    ]
