# Generated by Django 5.0.14 on 2026-02-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_create_equipmentphysicaltype_table'),
        ('catalog', '0008_sync_catalog_schema'),
    ]

    operations = [
    ]
