# Generated by Django 5.0.14 on 2026-02-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_equipmentmodule_physical_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.equipmentcategory', verbose_name='Родительская категория'),
        ),
    ]
