# Generated by Django 5.0.14 on 2026-02-16 10:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurator", "0002_alter_configuration_main_category_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="manager_comment",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quoted_price",
        ),
        migrations.AddField(
            model_name="order",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Название предприятия"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="order",
            name="configuration",
            field=models.OneToOneField(
                blank=True,
                help_text="Из какой конфигурации был создан заказ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order",
                to="configurator.configuration",
                verbose_name="Конфигурация",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default="TEMP", max_length=50, unique=True, verbose_name="Номер заказа"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("processing", "В обработке"),
                    ("quoted", "Счет выставлен"),
                    ("completed", "Завершен"),
                    ("canceled", "Отменен"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Итоговая стоимость",
            ),
        ),
    ]
