# Generated by Django 5.0.14 on 2026-02-16 11:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurator", "0002_alter_configuration_main_category_and_more"),
        ("orders", "0002_remove_order_manager_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="configuration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order",
                to="configurator.configuration",
                verbose_name="Конфигурация",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Общая стоимость",
            ),
        ),
    ]
