# Generated by Django 5.0.14 on 2026-02-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstatushistory_order_manager_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PRODUCTION', 'In production'), ('COMPLETED', 'Completed')], max_length=16),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PRODUCTION', 'In production'), ('COMPLETED', 'Completed')], max_length=16),
        ),
    ]
