# Generated by Django 5.0.14 on 2026-02-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_orders_orde_manager_feb8d0_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="quoted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
