# Generated by Django 5.0.14 on 2026-02-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_completed_at_order_quoted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("IN_REVIEW", "In review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("IN_PRODUCTION", "In production"),
                    ("COMPLETED", "Completed"),
                ],
                db_index=True,
                default="NEW",
                max_length=16,
            ),
        ),
    ]
