# Generated by Django 5.0.14 on 2026-02-07 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Новая конфигурация', max_length=255, verbose_name='Название конфигурации')),
                ('description', models.TextField(blank=True, verbose_name='Описание конфигурации')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('valid', 'Валидная'), ('invalid', 'Невалидная')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('compatibility_errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки совместимости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='catalog.equipmenttype', verbose_name='Тип оборудования')),
                ('modules', models.ManyToManyField(blank=True, related_name='configurations', to='catalog.equipmentmodule', verbose_name='Модули')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурации',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='configurato_user_id_1a98eb_idx'), models.Index(fields=['created_at'], name='configurato_created_ff4439_idx')],
            },
        ),
    ]
