# Generated by Django 5.0.14 on 2026-02-09 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_config', models.JSONField(blank=True, default=dict, help_text='РџР°СЂР°РјРµС‚СЂС‹ РєРѕРЅС‚РµР№РЅРµСЂР° РІ С„РѕСЂРјР°С‚Рµ JSON', verbose_name='РљРѕРЅС„РёРіСѓСЂР°С†РёСЏ РєРѕРЅС‚РµР№РЅРµСЂР°')),
                ('name', models.CharField(max_length=200, verbose_name='РќР°Р·РІР°РЅРёРµ РєРѕРЅС„РёРіСѓСЂР°С†РёРё')),
                ('description', models.TextField(blank=True, verbose_name='РћРїРёСЃР°РЅРёРµ')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='РћР±С‰Р°СЏ СЃС‚РѕРёРјРѕСЃС‚СЊ')),
                ('status', models.CharField(choices=[('draft', 'Р§РµСЂРЅРѕРІРёРє'), ('submitted', 'РћС‚РїСЂР°РІР»РµРЅ РїСЂРѕРёР·РІРѕРґРёС‚РµР»СЋ'), ('processing', 'Р’ РѕР±СЂР°Р±РѕС‚РєРµ'), ('quoted', 'РЎС‡РµС‚ РІС‹СЃС‚Р°РІР»РµРЅ'), ('completed', 'Р—Р°РІРµСЂС€РµРЅ')], default='draft', max_length=20, verbose_name='РЎС‚Р°С‚СѓСЃ')),
                ('order_number', models.CharField(blank=True, max_length=50, verbose_name='РќРѕРјРµСЂ Р·Р°РєР°Р·Р°')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='РќР°РёРјРµРЅРѕРІР°РЅРёРµ РїСЂРµРґРїСЂРёСЏС‚РёСЏ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='РўРµР»РµС„РѕРЅ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Р”Р°С‚Р° СЃРѕР·РґР°РЅРёСЏ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Р”Р°С‚Р° РѕР±РЅРѕРІР»РµРЅРёСЏ')),
                ('main_category', models.ForeignKey(help_text='Р”Р“РЈ РёР»Рё РљРѕРјРїСЂРµСЃСЃРѕСЂРЅР°СЏ СѓСЃС‚Р°РЅРѕРІРєР°', on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='catalog.equipmentcategory', verbose_name='РћСЃРЅРѕРІРЅРѕР№ С‚РёРї РѕР±РѕСЂСѓРґРѕРІР°РЅРёСЏ')),
                ('sub_category', models.ForeignKey(help_text='РљРѕРЅРєСЂРµС‚РЅР°СЏ С…Р°СЂР°РєС‚РµСЂРёСЃС‚РёРєР°, РЅР°РїСЂРёРјРµСЂ: Р”Р“РЈ РґРѕ 50 РєР’С‚', on_delete=django.db.models.deletion.CASCADE, related_name='sub_configurations', to='catalog.equipmentcategory', verbose_name='РџРѕРґРєР°С‚РµРіРѕСЂРёСЏ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to=settings.AUTH_USER_MODEL, verbose_name='РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ')),
            ],
            options={
                'verbose_name': 'РљРѕРЅС„РёРіСѓСЂР°С†РёСЏ',
                'verbose_name_plural': 'РљРѕРЅС„РёРіСѓСЂР°С†РёРё',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='РљРѕР»РёС‡РµСЃС‚РІРѕ')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.configuration')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.equipmentmodule')),
            ],
            options={
                'verbose_name': 'РњРѕРґСѓР»СЊ РІ РєРѕРЅС„РёРіСѓСЂР°С†РёРё',
                'verbose_name_plural': 'РњРѕРґСѓР»Рё РІ РєРѕРЅС„РёРіСѓСЂР°С†РёСЏС…',
                'unique_together': {('configuration', 'module')},
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='modules',
            field=models.ManyToManyField(related_name='configurations', through='configurator.ConfigurationModule', to='catalog.equipmentmodule', verbose_name='Р’С‹Р±СЂР°РЅРЅС‹Рµ РјРѕРґСѓР»Рё'),
        ),
    ]
