# Generated by Django 5.0.14 on 2026-02-11 16:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_engineeringsystemgroup_engineeringsystemoption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Параметры контейнера в формате JSON",
                        verbose_name="Конфигурация контейнера",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название конфигурации"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Общая стоимость",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("submitted", "Отправлен производителю"),
                            ("processing", "В обработке"),
                            ("quoted", "Счет выставлен"),
                            ("completed", "Завершен"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Номер заказа"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название предприятия"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "main_category",
                    models.ForeignKey(
                        help_text="ДГУ или Компрессорная установка",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="catalog.equipmentcategory",
                        verbose_name="Основной тип оборудования",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        help_text="Конкретная характеристика, например: ДГУ до 50 кВт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_configurations",
                        to="catalog.equipmentcategory",
                        verbose_name="Подкатегория",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конфигурация",
                "verbose_name_plural": "Конфигурации",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationEngineeringSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "custom_parameters",
                    models.JSONField(
                        blank=True,
                        help_text="Дополнительные настройки в формате JSON",
                        null=True,
                        verbose_name="Пользовательские параметры",
                    ),
                ),
                (
                    "price_at_selection",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена на момент выбора",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineering_items",
                        to="configurator.configuration",
                    ),
                ),
                (
                    "engineering_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuration_items",
                        to="catalog.engineeringsystemoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выбранная инженерная система",
                "verbose_name_plural": "Выбранные инженерные системы",
            },
        ),
        migrations.AddField(
            model_name="configuration",
            name="engineering_systems",
            field=models.ManyToManyField(
                blank=True,
                related_name="configurations",
                through="configurator.ConfigurationEngineeringSystem",
                to="catalog.engineeringsystemoption",
                verbose_name="Инженерные системы",
            ),
        ),
        migrations.CreateModel(
            name="ConfigurationModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_items",
                        to="configurator.configuration",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuration_items",
                        to="catalog.equipmentmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выбранный модуль",
                "verbose_name_plural": "Выбранные модули",
            },
        ),
        migrations.AddField(
            model_name="configuration",
            name="modules",
            field=models.ManyToManyField(
                blank=True,
                related_name="configurations",
                through="configurator.ConfigurationModule",
                to="catalog.equipmentmodule",
                verbose_name="Выбранные модули",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationengineeringsystem",
            constraint=models.UniqueConstraint(
                fields=("configuration", "engineering_system"),
                name="uniq_config_engineering",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationmodule",
            constraint=models.UniqueConstraint(
                fields=("configuration", "module"), name="uniq_config_module"
            ),
        ),
    ]
