# Generated by Django 5.0.14 on 2026-02-16 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_equipmentcategory_parent"),
        ("configurator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="main_category",
            field=models.ForeignKey(
                blank=True,
                help_text="ДГУ или Компрессорная установка",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="catalog.equipmentcategory",
                verbose_name="Основной тип оборудования",
            ),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Конкретная характеристика, например: ДГУ до 50 кВт",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_configurations",
                to="catalog.equipmentcategory",
                verbose_name="Подкатегория",
            ),
        ),
    ]
