# Generated by Django 5.0.14 on 2026-02-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_alter_configuration_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
