# Generated by Django 5.0.14 on 2026-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                default="Компания не указана",
                help_text="Обязательное поле по ТЗ",
                max_length=200,
                verbose_name="Название предприятия",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="confirmation_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Токен отправлен"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="confirmation_token",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Токен подтверждения",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="После подтверждения email появляется доступ к форме предрасчёта",
                verbose_name="Email подтверждён",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Пользователь заблокирован и не может создавать конфигурации",
                verbose_name="Заблокирован",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=True, verbose_name="Заказчик"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="Менеджер"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последняя активность"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Должность"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Обязательное поле по ТЗ",
                max_length=254,
                unique=True,
                verbose_name="Email адрес",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Группы, к которым принадлежит пользователь.",
                related_name="custom_user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="Группы",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Необязательное поле по ТЗ",
                max_length=20,
                null=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Конкретные права для этого пользователя.",
                related_name="custom_user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="Права пользователя",
            ),
        ),
    ]
